# Generated by Django 6.0.3 on 2026-03-20 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('police_auth', '0001_initial'),
    ]

    operations = [
    ]
